import type { Metadata } from "next";

import { getSession } from "@/actions/authAction";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LoginLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  if (session.isLoggedIn) redirect("/");

  return <div>{children}</div>;
}
